
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNSteerpathSmartMapSpec.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeSmartLocationManagerSpecJSI_startUpdatingLocation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "startUpdatingLocation", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartLocationManagerSpecJSI_stopUpdatingLocation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "stopUpdatingLocation", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartLocationManagerSpecJSI_addListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "addListener", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartLocationManagerSpecJSI_removeListeners(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeListeners", "(D)V", args, count, cachedMethodId);
}

NativeSmartLocationManagerSpecJSI::NativeSmartLocationManagerSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["startUpdatingLocation"] = MethodMetadata {0, __hostFunction_NativeSmartLocationManagerSpecJSI_startUpdatingLocation};
  methodMap_["stopUpdatingLocation"] = MethodMetadata {0, __hostFunction_NativeSmartLocationManagerSpecJSI_stopUpdatingLocation};
  methodMap_["addListener"] = MethodMetadata {1, __hostFunction_NativeSmartLocationManagerSpecJSI_addListener};
  methodMap_["removeListeners"] = MethodMetadata {1, __hostFunction_NativeSmartLocationManagerSpecJSI_removeListeners};
}
static facebook::jsi::Value __hostFunction_NativeSmartMapManagerSpecJSI_start(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "start", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartMapManagerSpecJSI_startWithConfig(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "startWithConfig", "(Lcom/facebook/react/bridge/ReadableMap;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartMapManagerSpecJSI_loginToLive(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "loginToLive", "(Lcom/facebook/react/bridge/ReadableMap;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartMapManagerSpecJSI_logoutFromLive(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "logoutFromLive", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeSmartMapManagerSpecJSI_fetchVersion(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "fetchVersion", "(Lcom/facebook/react/bridge/Callback;)V", args, count, cachedMethodId);
}

NativeSmartMapManagerSpecJSI::NativeSmartMapManagerSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["start"] = MethodMetadata {1, __hostFunction_NativeSmartMapManagerSpecJSI_start};
  methodMap_["startWithConfig"] = MethodMetadata {1, __hostFunction_NativeSmartMapManagerSpecJSI_startWithConfig};
  methodMap_["loginToLive"] = MethodMetadata {1, __hostFunction_NativeSmartMapManagerSpecJSI_loginToLive};
  methodMap_["logoutFromLive"] = MethodMetadata {0, __hostFunction_NativeSmartMapManagerSpecJSI_logoutFromLive};
  methodMap_["fetchVersion"] = MethodMetadata {1, __hostFunction_NativeSmartMapManagerSpecJSI_fetchVersion};
}

std::shared_ptr<TurboModule> RNSteerpathSmartMapSpec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "SmartLocationManager") {
    return std::make_shared<NativeSmartLocationManagerSpecJSI>(params);
  }
  if (moduleName == "SmartMapManager") {
    return std::make_shared<NativeSmartMapManagerSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
