source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/steerpath/steerpath-smart-sdk-podspec.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/cli-platform-ios/native_modules'

# 2026 Standard: iOS 15.1+ is required for the latest TurboModule performance
platform :ios, '15.1'
prepare_react_native_project!

target 'example' do
  # Automatically handles autolinking for the library you are developing
  config = use_native_modules!

  # Flags are now streamlined; Fabric and New Arch are enabled by default in 0.83
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true, # Enabled for 2026 New Arch performance
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
    # Modern post_install handles Apple Silicon and Xcode settings automatically
    react_native_post_install(installer)
    
    # 2026 Workaround: Ensure Steerpath (or any private pod) maps correctly
    # to the New Architecture headers if they aren't fully migrated.
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end