source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/steerpath/steerpath-smart-sdk-podspec.git'

ENV['RCT_NEW_ARCH_ENABLED'] = '0' # change it to 1 to enable New Architecture, and check info.plist files as well

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# 2026 Standard: iOS 15.1+ is required for the latest TurboModule performance
platform :ios, '15.1'
prepare_react_native_project!


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'example' do
  # Automatically handles autolinking for the library you are developing
  config = use_native_modules!

  # Flags are now streamlined; Fabric and New Arch are enabled by default in 0.83
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )


  post_install do |installer|
    # Modern post_install handles Apple Silicon and Xcode settings automatically
    react_native_post_install(installer)
  end
end