package com.steerpath.rnsmartmap;

import android.util.Log;
import androidx.annotation.NonNull;

import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReadableMap;
import com.steerpath.smart.SmartSDK;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;

// This is the class generated by Codegen
import com.steerpath.rnsmartmap.NativeSmartMapManagerSpec;

public class RNSmartMapManager extends NativeSmartMapManagerSpec {

    public static final String NAME = "RNSmartMapManager";
    private final ReactApplicationContext appContext;

    public RNSmartMapManager(ReactApplicationContext reactContext) {
        super(reactContext);
        this.appContext = reactContext;
    }

    @Override
    @NonNull
    public String getName() {
        return NAME;
    }

    @Override
    public void start(String apiKey) {
        appContext.runOnUiQueueThread(() -> SmartSDK.getInstance().start(appContext, apiKey));
    }

    @Override
    public void startWithConfig(ReadableMap map) {
        String apiKey = map.getString("apiKey");
        if (map.hasKey("configFilePath")) {
            String filePath = map.getString("configFilePath");
            if (filePath != null) {
                File file = new File(filePath);
                appContext.runOnUiQueueThread(() -> SmartSDK.getInstance().start(appContext, apiKey, file));
            }
        } else if (map.hasKey("configString")) {
            String configString = map.getString("configString");
            if (configString != null) {
                appContext.runOnUiQueueThread(() -> SmartSDK.getInstance().start(appContext, apiKey, configString));
            }
        }
    }

    @Override
    public void loginToLive(ReadableMap map) {
        if (map != null) {
            try {
                JSONObject obj = Utils.convertMapToJson(map);
                appContext.runOnUiQueueThread(() -> SmartSDK.getInstance().loginToLive(appContext, obj));
            } catch (JSONException e) {
                Log.e(NAME, "Failed to login into Steerpath live service");
            }
        }
    }

    @Override
    public void logoutFromLive() {
        appContext.runOnUiQueueThread(() -> SmartSDK.getInstance().logoutFromLive(appContext));
    }

    @Override
    public void fetchVersion(Callback callback) {
        // Based on our simplified JS Spec (returning just a string)
        JSONObject versions = SmartSDK.getVersions();
        String version = "Unknown";
        try {
            version = versions.getString("smartSDKVersion");
        } catch (JSONException e) {
            Log.e(NAME, "Error fetching version", e);
        }

        // Even for a single string, callback.invoke() expects arguments
        // that match the JS side.
        callback.invoke(version);
    }
}