//
//  RNSmartLocationManager.h
//  SteerpathSmartMapSdk
//
//  Created by Roope Vilo on 24.5.2023.
//  Copyright © 2023 Facebook. All rights reserved.
//

#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@import SteerpathSmartSDK;

// Import the Spec generated by Codegen
#ifdef RCT_NEW_ARCH_ENABLED
#import "RNSteerpathSmartMapSpec.h"
@interface RNSmartLocationManager : RCTEventEmitter <NativeSmartLocationManagerSpec, SPSmartLocationManagerDelegate>
#else
@interface RNSmartLocationManager : RCTEventEmitter <RCTBridgeModule, SPSmartLocationManagerDelegate>
#endif

@end
