//
//  RNSmartMapManager.h
//  SteerpathOfficeApp
//
//  Created by Jarvis Luong on 30/07/2019.
//  Copyright © 2019 Facebook. All rights reserved.
//

#import <React/RCTBridgeModule.h>

@import SteerpathSmartSDK;

// When New Architecture is enabled, we import the Spec generated by Codegen
#ifdef RCT_NEW_ARCH_ENABLED
#import "RNSteerpathSmartMapSpec.h" // Name matches package.json codegenConfig
@interface RNSmartMapManager : NSObject <NativeRNSmartMapManagerSpec>
#else
@interface RNSmartMapManager : NSObject <RCTBridgeModule>
#endif

@end
