/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {createStackNavigator, createAppContainer} from 'react-navigation';
import { MapScreenWithContext } from './screens/MapScreenWithContext';

const rootStack = createStackNavigator({
    Home: {
        screen: MapScreenWithContext,
        navigationOptions: ({ navigation }) => ({
            header: null
        })
    }
  });

  const App = createAppContainer(rootStack);
  export default App;