/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


template <typename T>
class JSI_EXPORT NativeSmartLocationManagerCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "SmartLocationManager";

protected:
  NativeSmartLocationManagerCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeSmartLocationManagerCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["startUpdatingLocation"] = MethodMetadata {.argCount = 0, .invoker = __startUpdatingLocation};
    methodMap_["stopUpdatingLocation"] = MethodMetadata {.argCount = 0, .invoker = __stopUpdatingLocation};
    methodMap_["addListener"] = MethodMetadata {.argCount = 1, .invoker = __addListener};
    methodMap_["removeListeners"] = MethodMetadata {.argCount = 1, .invoker = __removeListeners};
  }
  
private:
  static jsi::Value __startUpdatingLocation(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::startUpdatingLocation) == 1,
      "Expected startUpdatingLocation(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::startUpdatingLocation,  static_cast<NativeSmartLocationManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __stopUpdatingLocation(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::stopUpdatingLocation) == 1,
      "Expected stopUpdatingLocation(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::stopUpdatingLocation,  static_cast<NativeSmartLocationManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __addListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::addListener) == 2,
      "Expected addListener(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::addListener,  static_cast<NativeSmartLocationManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __removeListeners(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeListeners) == 2,
      "Expected removeListeners(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeListeners,  static_cast<NativeSmartLocationManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }
};


#pragma mark - NativeSmartMapManagerConfigSDK

template <typename P0, typename P1, typename P2>
struct NativeSmartMapManagerConfigSDK {
  P0 apiKey;
  P1 configFilePath;
  P2 configString;
  bool operator==(const NativeSmartMapManagerConfigSDK &other) const {
    return apiKey == other.apiKey && configFilePath == other.configFilePath && configString == other.configString;
  }
};

template <typename T>
struct NativeSmartMapManagerConfigSDKBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.apiKey)>(rt, value.getProperty(rt, "apiKey"), jsInvoker),
      bridging::fromJs<decltype(types.configFilePath)>(rt, value.getProperty(rt, "configFilePath"), jsInvoker),
      bridging::fromJs<decltype(types.configString)>(rt, value.getProperty(rt, "configString"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String apiKeyToJs(jsi::Runtime &rt, decltype(types.apiKey) value) {
    return bridging::toJs(rt, value);
  }
  static std::optional<jsi::String> configFilePathToJs(jsi::Runtime &rt, decltype(types.configFilePath) value) {
    return bridging::toJs(rt, value);
  }
  static std::optional<jsi::String> configStringToJs(jsi::Runtime &rt, decltype(types.configString) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "apiKey", bridging::toJs(rt, value.apiKey, jsInvoker));
    if (value.configFilePath) {
      result.setProperty(rt, "configFilePath", bridging::toJs(rt, value.configFilePath.value(), jsInvoker));
    }
    if (value.configString) {
      result.setProperty(rt, "configString", bridging::toJs(rt, value.configString.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeSmartMapManagerLiveConfig

template <typename P0, typename P1>
struct NativeSmartMapManagerLiveConfig {
  P0 transmit;
  P1 receive;
  bool operator==(const NativeSmartMapManagerLiveConfig &other) const {
    return transmit == other.transmit && receive == other.receive;
  }
};

template <typename T>
struct NativeSmartMapManagerLiveConfigBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.transmit)>(rt, value.getProperty(rt, "transmit"), jsInvoker),
      bridging::fromJs<decltype(types.receive)>(rt, value.getProperty(rt, "receive"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::Object transmitToJs(jsi::Runtime &rt, decltype(types.transmit) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::Object receiveToJs(jsi::Runtime &rt, decltype(types.receive) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    if (value.transmit) {
      result.setProperty(rt, "transmit", bridging::toJs(rt, value.transmit.value(), jsInvoker));
    }
    if (value.receive) {
      result.setProperty(rt, "receive", bridging::toJs(rt, value.receive.value(), jsInvoker));
    }
    return result;
  }
};


template <typename T>
class JSI_EXPORT NativeSmartMapManagerCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "SmartMapManager";

protected:
  NativeSmartMapManagerCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeSmartMapManagerCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["start"] = MethodMetadata {.argCount = 1, .invoker = __start};
    methodMap_["startWithConfig"] = MethodMetadata {.argCount = 1, .invoker = __startWithConfig};
    methodMap_["loginToLive"] = MethodMetadata {.argCount = 1, .invoker = __loginToLive};
    methodMap_["logoutFromLive"] = MethodMetadata {.argCount = 0, .invoker = __logoutFromLive};
    methodMap_["fetchVersion"] = MethodMetadata {.argCount = 1, .invoker = __fetchVersion};
  }
  
private:
  static jsi::Value __start(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::start) == 2,
      "Expected start(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::start,  static_cast<NativeSmartMapManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __startWithConfig(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::startWithConfig) == 2,
      "Expected startWithConfig(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::startWithConfig,  static_cast<NativeSmartMapManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt));return jsi::Value::undefined();
  }

  static jsi::Value __loginToLive(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::loginToLive) == 2,
      "Expected loginToLive(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::loginToLive,  static_cast<NativeSmartMapManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt));return jsi::Value::undefined();
  }

  static jsi::Value __logoutFromLive(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::logoutFromLive) == 1,
      "Expected logoutFromLive(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::logoutFromLive,  static_cast<NativeSmartMapManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __fetchVersion(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::fetchVersion) == 2,
      "Expected fetchVersion(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::fetchVersion,  static_cast<NativeSmartMapManagerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt).asFunction(rt));return jsi::Value::undefined();
  }
};

} // namespace facebook::react
